apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: demo-environment
  title: Demo Env
  description: Create a demo environment. 
  tags:
    - aws
    - recommended
    - crossplane
    - environments
spec:
  owner: admin
  type: repository
  parameters:
    - title: Provide some information
      required:
        - component_id
        - description
      properties:
        component_id:
          title: Name
          type: string
          description: Name of the environment
        description:
          title: Description
          type: string
          description: Describe your environment
        kubernetes_version:
          title: Kubernetes Version
          type: string
          description: Name of the environment
          default: "1.26"
        num_nodes:
          title: Nodes
          type: integer
          description: Number of nodes
          default: 3
        node_size:
          title: Node Size
          type: string
          description: Size of nodes to be used
          default: small
          enum:
            - small
            - medium
            - large
        prometheus_version:
          title: Prometheus Version
          type: string
          description: Version of Prometheus to use
          default: "1.26"
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          kubernetes_version: ${{ parameters.kubernetes_version }}
          num_nodes: ${{ parameters.num_nodes }}
          node_size: ${{ parameters.node_size }}
          prometheus_version: ${{ parameters.prometheus_version }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: github.com?repo=infra&owner=efidemos

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/efidemos/infra/blob/main/catalog/${{ parameters.component_id }}-catalog.yaml

  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
