apiVersion: punasusi.com/v1alpha1
kind: ClusterClaim
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: ${{ values.component_id }}
  labels:
    cluster-owner: ${{ values.component_id }}
spec:
  id: ${{ values.component_id }}
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 3
    version: "1.23"
